# Generated by Django 4.1.5 on 2023-04-15 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('advert_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('post_vacancy', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_post', models.IntegerField(blank=True, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, choices=[(0, 'EXTERNAL'), (1, 'INTERNAL')], db_index=True, default=0, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('duties_responsibilities', models.TextField(blank=True, null=True)),
                ('job_requirements', models.TextField(blank=True, null=True)),
                ('pay_type', models.IntegerField(blank=True, choices=[(0, 'MONTHLY'), (1, 'YEARLY')], default=0, null=True)),
                ('currency', models.CharField(default='Ksh', max_length=10)),
                ('basic_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('house_allowance', models.CharField(blank=True, max_length=100, null=True)),
                ('commuter_allowance', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_allowance', models.CharField(blank=True, default='As provided in TSC Secretariat', max_length=100, null=True)),
                ('medical_scheme', models.CharField(blank=True, default='As provided in the TSC Secretariat Medical Scheme', max_length=100, null=True)),
                ('is_closed', models.IntegerField(blank=True, choices=[(0, 'OPEN'), (1, 'CLOSED'), (3, 'DRAFT')], default=0, null=True)),
                ('category_target_group', models.IntegerField(blank=True, choices=[(0, 'SECRETARIATS'), (1, 'TEACHERS')], default=0, null=True)),
                ('term_of_service', models.IntegerField(blank=True, choices=[(0, 'PERMANENT'), (1, 'CONTRACT'), (2, 'INTERN')], default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
