# Generated by Django 4.1.5 on 2023-04-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('post_vacancy', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_post', models.IntegerField(blank=True, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('0', 'EXTERNAL'), ('1', 'INTERNAL')], db_index=True, max_length=15, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('duties_responsibilities', models.TextField(blank=True, null=True)),
                ('pay_date', models.CharField(blank=True, max_length=30, null=True)),
                ('currency', models.CharField(default='Ksh', max_length=10)),
                ('basic_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('house_allowance', models.CharField(blank=True, max_length=100, null=True)),
                ('commuter_allowance', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_allowance', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_scheme', models.CharField(blank=True, max_length=100, null=True)),
                ('is_closed', models.CharField(blank=True, choices=[('0', 'OPEN'), ('1', 'CLOSED')], max_length=10, null=True)),
                ('category_target_group', models.CharField(blank=True, choices=[('0', 'SECRETARIATS'), ('1', 'TEACHERS')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
