# Generated by Django 4.1.5 on 2023-04-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='term_of_service',
            field=models.CharField(blank=True, choices=[('0', 'PERMANENT'), ('1', 'CONTRACT'), ('2', 'INTERN')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='is_closed',
            field=models.CharField(blank=True, choices=[('0', 'OPEN'), ('1', 'CLOSED'), ('3', 'DRAFT')], max_length=10, null=True),
        ),
    ]
