# Generated by Django 4.1.5 on 2023-04-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_advert_term_of_service_alter_advert_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='pay_date',
        ),
        migrations.AddField(
            model_name='advert',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('0', 'MONTHLY'), ('1', 'YEARLY')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='leave_allowance',
            field=models.CharField(blank=True, default='As provided in TSC Secretariat', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='medical_scheme',
            field=models.CharField(blank=True, default='As provided in the TSC Secretariat Medical Scheme', max_length=100, null=True),
        ),
    ]
