# Generated by Django 4.1.5 on 2023-04-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_remove_advert_pay_date_advert_pay_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='job_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
